//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_EX_QLTT.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EF_EX_QLTT.Helper.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chua ton tai!.
        /// </summary>
        internal static string ChuaTonTai {
            get {
                return ResourceManager.GetString("ChuaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sach Trong!.
        /// </summary>
        internal static string DanhSachTrong {
            get {
                return ResourceManager.GetString("DanhSachTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong duoc de trong, dinh dang phai hop le.
        /// </summary>
        internal static string ErrBatBuocHopLe {
            get {
                return ResourceManager.GetString("ErrBatBuocHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: bắt buộc, từ 10-100 kí tự.
        /// </summary>
        internal static string ErrEmail {
            get {
                return ResourceManager.GetString("ErrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ten bắt buộc, từ 6-50 kí tự.
        /// </summary>
        internal static string ErrHoten {
            get {
                return ResourceManager.GetString("ErrHoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngsinh bắt buộc.
        /// </summary>
        internal static string ErrNgsinh {
            get {
                return ResourceManager.GetString("ErrNgsinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT: bắt buộc, từ 10-15 kí tự.
        /// </summary>
        internal static string ErrSDT {
            get {
                return ResourceManager.GetString("ErrSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap DiaChi:.
        /// </summary>
        internal static string InDC {
            get {
                return ResourceManager.GetString("InDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap NgayDK:.
        /// </summary>
        internal static string InDK {
            get {
                return ResourceManager.GetString("InDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap Email:.
        /// </summary>
        internal static string InEmail {
            get {
                return ResourceManager.GetString("InEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap Gioi Tinh:.
        /// </summary>
        internal static string InGT {
            get {
                return ResourceManager.GetString("InGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ID Lop:
        ///.
        /// </summary>
        internal static string InLop {
            get {
                return ResourceManager.GetString("InLop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap NgaySinh.
        /// </summary>
        internal static string InNgsinh {
            get {
                return ResourceManager.GetString("InNgsinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ho ten:.
        /// </summary>
        internal static string inputHoten {
            get {
                return ResourceManager.GetString("inputHoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap SDT:.
        /// </summary>
        internal static string InSDT {
            get {
                return ResourceManager.GetString("InSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuc hien thanh cong!.
        /// </summary>
        internal static string ThanhCong {
            get {
                return ResourceManager.GetString("ThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuc hien that bai!.
        /// </summary>
        internal static string ThatBai {
            get {
                return ResourceManager.GetString("ThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung ma!.
        /// </summary>
        internal static string TrungMa {
            get {
                return ResourceManager.GetString("TrungMa", resourceCulture);
            }
        }
    }
}
